---
logs:
  json: false
metrics:
  endpoint: 127.0.0.1:10124
channel:
  tokio:
    worker_threads: 2
    affinity: 0-1
  source:
    # transport: quic
    # source: richat # valid: richat, dragons_mouth
    # endpoint: 127.0.0.1:10100
    # local_addr: "[::]:0"
    # expected_rtt: 100
    # max_stream_bandwidth: 12_500_000 # 100Mbits with 100ms latency
    # max_idle_timeout: 30ms
    # server_name: null # localhost
    # recv_streams: 1
    # max_backlog: null
    # insecure: false
    # cert: null
    # x_token: null
    # ---
    transport: tcp
    source: richat # valid: richat, dragons_mouth
    endpoint: 127.0.0.1:10101
    keepalive: null
    nodelay: true
    recv_buffer_size: null
    x_token: null
    # ---
    # transport: grpc
    # source: richat # valid: richat, dragons_mouth
    # endpoint: http://127.0.0.1:10102
    # ca_certificate: null
    # connect_timeout: null
    # buffer_size: null
    # http2_adaptive_window: null
    # http2_keep_alive_interval: null
    # initial_connection_window_size: null
    # initial_stream_window_size: null
    # keep_alive_timeout: null
    # keep_alive_while_idle: false
    # tcp_keepalive: 15s
    # tcp_nodelay: true
    # timeout: null
    # max_decoding_message_size: 16_777_216 # 16MiB
    # compression:
    #   accept: ["gzip", "zstd"]
    #   send: ["gzip", "zstd"]
    # x_token: null
  config:
    max_messages: 2_097_152
    max_bytes: 16_106_127_360
    parser: prost
    parser_affinity: 0-1
apps:
  tokio:
    worker_threads: 2
    affinity: 2-3
  richat:
    quic:
      endpoint: '127.0.0.1:10100'
      tls_config:
        # cert: /path/to/cert.cert
        # key: /path/to/key.key
        self_signed_alt_names:
          - localhost
      expected_rtt: 100
      max_stream_bandwidth: 12500000
      max_recv_streams: 16
      x_tokens: []
    tcp:
      endpoint: '127.0.0.1:10101'
      backlog: 1024
      keepalive: null
      nodelay: true
      send_buffer_size: null
      x_tokens: []
    grpc:
      endpoint: '127.0.0.1:10102'
      tls_config:
        cert: /path/to/cert.cert
        key: /path/to/key.key
      compression:
        accept:
          - gzip
          - zstd
        send:
          - gzip
          - zstd
      max_decoding_message_size: '4_194_304'
      server_tcp_keepalive: 20s
      server_tcp_nodelay: true
      server_http2_adaptive_window: null
      server_http2_keepalive_interval: null
      server_http2_keepalive_timeout: null
      server_initial_connection_window_size: null
      server_initial_stream_window_size: null
  grpc:
    server:
      endpoint: 127.0.0.1:10102
      tls_config:
        cert: /path/to/cert.cert
        key: /path/to/key.key
      compression:
        accept:
        - gzip
        - zstd
        send:
        - gzip
        - zstd
      max_decoding_message_size: 4_194_304 # 4MiB
      server_tcp_keepalive: 20s
      server_tcp_nodelay: true
      server_http2_adaptive_window:
      server_http2_keepalive_interval:
      server_http2_keepalive_timeout:
      server_initial_connection_window_size:
      server_initial_stream_window_size:
    workers:
      threads: 2
      affinity: 4-5
      messages_cached_max: 1_024
    stream:
      messages_len_max: 16_777_216
      messages_max_per_tick: 100
      ping_iterval: 15s
    unary:
      enabled: true
      affinity: 4-5
      requests_queue_size: 100
    filters:
      name_max: 128
      accounts:
        max: 1
        any: false
        account_max: 10
        account_reject:
        - TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
        owner_max: 10
        owner_reject:
        - '11111111111111111111111111111111'
        data_slice_max: 2
      slots:
        max: 1
      transactions:
        max: 1
        any: false
        account_include_max: 10
        account_include_reject:
        - TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
        account_exclude_max: 10
        account_required_max: 10
      transactions_status:
        max: 1
        any: false
        account_include_max: 10
        account_include_reject:
        - TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
        account_exclude_max: 10
        account_required_max: 10
      entries:
        max: 1
      blocks_meta:
        max: 1
      blocks:
        max: 1
        account_include_max: 10
        account_include_any: false
        account_include_reject:
        - TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
        include_transactions: true
        include_accounts: false
        include_entries: false
    x_token: []
  pubsub:
    endpoint: 0.0.0.0:8000
    tcp_nodelay: true
    tls_config:
      # cert: /path/to/cert.cert
      # key: /path/to/key.key
      self_signed_alt_names:
        - localhost
    recv_max_message_size: 4_096
    enable_block_subscription: false
    enable_transaction_subscription: false
    clients_requests_channel_size: 8_192
    subscriptions_worker_affinity: 0
    subscriptions_workers_count: 2
    subscriptions_workers_affinity: 0-1
    subscriptions_max_clients_request_per_tick: 32
    subscriptions_max_messages_per_commitment_per_tick: 256
    notifications_messages_max_count: 10_000_000
    notifications_messages_max_bytes: 34_359_738_368
    signatures_cache_max: 1_228_800
    signatures_cache_slots_max: 150
