permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - '.github/workflows/release-plugin-agave.yml'
  push:
    branches:
      - master
      - agave-v2.0
      - agave-v2.1
      - agave-v2.2
    tags:
      - 'plugin-agave-v*'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ["${{ matrix.os }}"]
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev

      - uses: fanatid/rust-github-ci-prepare@master
        with:
          cache-version: v0002-plugin-agave

      - name: Build richat plugin agave
        run: |
          cargo build -p richat-plugin-agave --release
          cd target/release && \
            mv richat-plugin-agave-config-check richat-plugin-agave-config-check-${{ matrix.os }} && \
            mv librichat_plugin_agave.so librichat_plugin_agave_${{ matrix.os }}.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: richat-plugin-agave-${{ matrix.os }}-${{ github.sha }}
          path: |
            target/release/richat-plugin-agave-config-check-${{ matrix.os }}
            target/release/librichat_plugin_agave_${{ matrix.os }}.so

      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/richat-plugin-agave-config-check-${{ matrix.os }}
            target/release/librichat_plugin_agave_${{ matrix.os }}.so
