concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - master
      - agave-v2.0
      - agave-v2.1
      - agave-v2.2
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ["${{ matrix.os }}"]
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev

      - uses: fanatid/rust-github-ci-prepare@master
        with:
          cache-version: v0003

      - name: cargo deny check advisories
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check advisories

      - name: run clippy
        run: cargo clippy --workspace --all-targets -- -Dwarnings

      - name: run clippy in plugin-fuzz
        run: cd plugin-agave/fuzz && cargo clippy --workspace --all-targets -- -Dwarnings

      - name: check features in `richat-cli`
        run: cargo check -p richat-cli --all-targets

      - name: check features in `richat-client`
        run: cargo check -p richat-client --all-targets

      - name: check features in `richat-filter`
        run: cargo check -p richat-filter --all-targets

      - name: check features in `richat-plugin-agave`
        run: cargo check -p richat-plugin-agave --all-targets

      - name: check features in `richat-plugin-agave` with all features
        run: cargo check -p richat-plugin-agave --all-targets --all-features

      - name: check features in `richat`
        run: cargo check -p richat --all-targets

      - name: check features in `richat-shared`
        run: cargo check -p richat-shared --all-targets

      - name: check features in `richat-shared`
        run: cargo check -p richat-shared --all-targets --no-default-features --features="config"

      - name: check features in `richat-shared`
        run: cargo check -p richat-shared --all-targets --no-default-features --features="five8"

      - name: check features in `richat-shared`
        run: cargo check -p richat-shared --all-targets --no-default-features --features="metrics"

      - name: check features in `richat-shared`
        run: cargo check -p richat-shared --all-targets --no-default-features --features="shutdown"

      - name: check features in `richat-shared`
        run: cargo check -p richat-shared --all-targets --no-default-features --features="transports"

      - name: check features in `richat-shared`
        run: cargo check -p richat-shared --all-targets --no-default-features --features="version"

      - name: run test
        run: cargo test --all-targets
