concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os:
          # - ubuntu-20.04
          - ubuntu-22.04
          # - ubuntu-24.04
    runs-on: ["${{ matrix.os }}"]
    steps:
      - uses: actions/checkout@v4

      - uses: fanatid/rust-github-ci-prepare@master

      - name: cargo deny check advisories
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check advisories

      - name: run clippy
        run: cargo clippy --workspace --all-targets -- -Dwarnings

      - name: run clippy in plugin-fuzz
        run: cd plugin/fuzz && cargo clippy --workspace --all-targets -- -Dwarnings

      - name: check features in `richat-cli`
        run: cargo check -p richat-cli --all-targets

      - name: check features in `richat-client`
        run: cargo check -p richat-client --all-targets

      - name: check features in `richat-plugin`
        run: cargo check -p richat-plugin --all-targets

      - name: check features in `richat`
        run: cargo check -p richat --all-targets

      - name: check features in `richat-shared`
        run: cargo check -p richat-shared --all-targets

      - name: run test
        run: cargo test --all-targets
